---
namespace: ednz_cloud
name: k3s
version: 0.3.0
readme: README.md
authors:
  - Bertrand Lanson <bertrand.lanson@protonmail.com>
description: your collection description
license: ["MIT"]
license_file: "LICENSE"
tags: ["tools", "rancher", "kubernetes", "k8s", "k3s"]
dependencies:
  kubernetes.core: ">=6.0.0"
  ansible.utils: ">=5.0.0"
  community.general: ">=9.0.0"
repository: https://gitlab.ednz.fr/ednz-cloud/ansible/collections/ednz_cloud.k3s
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []
