---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Run k3s tests"
      ansible.builtin.include_role:
        name: ednz_cloud.k3s.k3s_tests
      vars:
        k3s_tests_include_tests:
          - cluster-health
          - labels
        k3s_tests_expected_labels:
          molecule-test: "true"
          test-environment: "openstack"
